"""fields for history

Revision ID: 775789ddf29e
Revises: 
Create Date: 2025-10-26 08:37:12.616171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775789ddf29e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('current_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('history', sa.Column('arrival_times', sa.JSON(), nullable=True))
    op.add_column('history', sa.Column('total_distance', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('total_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'total_time')
    op.drop_column('history', 'total_distance')
    op.drop_column('history', 'arrival_times')
    op.drop_column('history', 'current_date')
    # ### end Alembic commands ###
